# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ejbosia/Programs/drawbot/c++

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ejbosia/Programs/drawbot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ejbosia/Programs/drawbot/CMakeFiles /home/ejbosia/Programs/drawbot/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ejbosia/Programs/drawbot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named drawbot

# Build rule for target.
drawbot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drawbot
.PHONY : drawbot

# fast build rule for target.
drawbot/fast:
	$(MAKE) -f CMakeFiles/drawbot.dir/build.make CMakeFiles/drawbot.dir/build
.PHONY : drawbot/fast

angle.o: angle.cpp.o

.PHONY : angle.o

# target to build an object file
angle.cpp.o:
	$(MAKE) -f CMakeFiles/drawbot.dir/build.make CMakeFiles/drawbot.dir/angle.cpp.o
.PHONY : angle.cpp.o

angle.i: angle.cpp.i

.PHONY : angle.i

# target to preprocess a source file
angle.cpp.i:
	$(MAKE) -f CMakeFiles/drawbot.dir/build.make CMakeFiles/drawbot.dir/angle.cpp.i
.PHONY : angle.cpp.i

angle.s: angle.cpp.s

.PHONY : angle.s

# target to generate assembly for a file
angle.cpp.s:
	$(MAKE) -f CMakeFiles/drawbot.dir/build.make CMakeFiles/drawbot.dir/angle.cpp.s
.PHONY : angle.cpp.s

contour.o: contour.cpp.o

.PHONY : contour.o

# target to build an object file
contour.cpp.o:
	$(MAKE) -f CMakeFiles/drawbot.dir/build.make CMakeFiles/drawbot.dir/contour.cpp.o
.PHONY : contour.cpp.o

contour.i: contour.cpp.i

.PHONY : contour.i

# target to preprocess a source file
contour.cpp.i:
	$(MAKE) -f CMakeFiles/drawbot.dir/build.make CMakeFiles/drawbot.dir/contour.cpp.i
.PHONY : contour.cpp.i

contour.s: contour.cpp.s

.PHONY : contour.s

# target to generate assembly for a file
contour.cpp.s:
	$(MAKE) -f CMakeFiles/drawbot.dir/build.make CMakeFiles/drawbot.dir/contour.cpp.s
.PHONY : contour.cpp.s

line.o: line.cpp.o

.PHONY : line.o

# target to build an object file
line.cpp.o:
	$(MAKE) -f CMakeFiles/drawbot.dir/build.make CMakeFiles/drawbot.dir/line.cpp.o
.PHONY : line.cpp.o

line.i: line.cpp.i

.PHONY : line.i

# target to preprocess a source file
line.cpp.i:
	$(MAKE) -f CMakeFiles/drawbot.dir/build.make CMakeFiles/drawbot.dir/line.cpp.i
.PHONY : line.cpp.i

line.s: line.cpp.s

.PHONY : line.s

# target to generate assembly for a file
line.cpp.s:
	$(MAKE) -f CMakeFiles/drawbot.dir/build.make CMakeFiles/drawbot.dir/line.cpp.s
.PHONY : line.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/drawbot.dir/build.make CMakeFiles/drawbot.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/drawbot.dir/build.make CMakeFiles/drawbot.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/drawbot.dir/build.make CMakeFiles/drawbot.dir/main.cpp.s
.PHONY : main.cpp.s

point.o: point.cpp.o

.PHONY : point.o

# target to build an object file
point.cpp.o:
	$(MAKE) -f CMakeFiles/drawbot.dir/build.make CMakeFiles/drawbot.dir/point.cpp.o
.PHONY : point.cpp.o

point.i: point.cpp.i

.PHONY : point.i

# target to preprocess a source file
point.cpp.i:
	$(MAKE) -f CMakeFiles/drawbot.dir/build.make CMakeFiles/drawbot.dir/point.cpp.i
.PHONY : point.cpp.i

point.s: point.cpp.s

.PHONY : point.s

# target to generate assembly for a file
point.cpp.s:
	$(MAKE) -f CMakeFiles/drawbot.dir/build.make CMakeFiles/drawbot.dir/point.cpp.s
.PHONY : point.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... drawbot"
	@echo "... angle.o"
	@echo "... angle.i"
	@echo "... angle.s"
	@echo "... contour.o"
	@echo "... contour.i"
	@echo "... contour.s"
	@echo "... line.o"
	@echo "... line.i"
	@echo "... line.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... point.o"
	@echo "... point.i"
	@echo "... point.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

